"""empty message

Revision ID: 14f3f5cbffb9
Revises: dbdbf747ae87
Create Date: 2021-07-08 14:04:35.738890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f3f5cbffb9'
down_revision = 'dbdbf747ae87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('role_user_id_fkey', 'role', type_='foreignkey')
    op.drop_column('role', 'user_id')
    op.add_column('auth', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'auth', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth', type_='foreignkey')
    op.drop_column('auth', 'role_id')
    op.add_column('role', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('role_user_id_fkey', 'role', 'auth', ['user_id'], ['id'])
    # ### end Alembic commands ###
