"""empty message

Revision ID: cad3862f124b
Revises: 14f3f5cbffb9
Create Date: 2021-07-08 14:43:31.181338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cad3862f124b'
down_revision = '14f3f5cbffb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'department', 'auth', ['user_id'], ['id'])
    op.drop_constraint('user_department_id_fkey', 'auth', type_='foreignkey')
    op.drop_column('auth', 'department_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_department_id_fkey', 'auth', 'department', ['department_id'], ['id'])
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_column('department', 'user_id')
    # ### end Alembic commands ###
